theme: jekyll-theme-minimal
show_downloads: null
title: [ - Abhinav Patel   - API designer and developer   - 4+ years of IT exp    - Learning everyday]
footer: false
logo: /assets/img/test_image.jpg


